apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rdfmgfd77-nodejs
  janus-idp.io/tekton: rdfmgfd77-nodejs
  backstage.io/kubernetes-id: rdfmgfd77-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rdfmgfd77-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
